PRAGMA foreign_keys = ON;
CREATE TABLE user (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, email_verified INTEGER NOT NULL DEFAULT 0, image TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, two_factor_enabled INTEGER DEFAULT 0);
CREATE TABLE session (id TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, ip_address TEXT, user_agent TEXT, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE);
CREATE INDEX session_user_idx ON session(user_id);
CREATE TABLE account (id TEXT PRIMARY KEY, issuer TEXT NOT NULL, account_id TEXT NOT NULL, provider_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, access_token TEXT, refresh_token TEXT, id_token TEXT, access_token_expires_at INTEGER, refresh_token_expires_at INTEGER, scope TEXT, password TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX account_user_idx ON account(user_id);
CREATE UNIQUE INDEX account_issuer_idx ON account(issuer,account_id);
CREATE TABLE verification (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER, updated_at INTEGER);
CREATE INDEX verification_identifier_idx ON verification(identifier);
CREATE TABLE passkey (id TEXT PRIMARY KEY, name TEXT, public_key TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, credential_id TEXT NOT NULL, counter INTEGER NOT NULL, device_type TEXT NOT NULL, backed_up INTEGER NOT NULL, transports TEXT, created_at INTEGER, aaguid TEXT);
CREATE INDEX passkey_user_idx ON passkey(user_id);
CREATE INDEX passkey_credential_idx ON passkey(credential_id);
CREATE TABLE two_factor (id TEXT PRIMARY KEY, secret TEXT NOT NULL, backup_codes TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, verified INTEGER DEFAULT 1, failed_verification_count INTEGER DEFAULT 0, locked_until INTEGER);
CREATE INDEX two_factor_user_idx ON two_factor(user_id);
CREATE TABLE rate_limit (id TEXT PRIMARY KEY, key TEXT NOT NULL UNIQUE, count INTEGER NOT NULL, last_request INTEGER NOT NULL);
CREATE TABLE workspace (owner_id TEXT PRIMARY KEY REFERENCES user(id) ON DELETE CASCADE, payload TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, monitoring INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL);
CREATE TABLE integration (owner_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, provider TEXT NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(owner_id,provider));
CREATE TABLE api_token (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, name TEXT NOT NULL, prefix TEXT NOT NULL, hash TEXT NOT NULL UNIQUE, scopes TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL, last_used_at TEXT);
CREATE INDEX api_token_owner_idx ON api_token(owner_id);
CREATE TABLE activity (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, action TEXT NOT NULL, summary TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX activity_owner_idx ON activity(owner_id,created_at);
CREATE TABLE operation (owner_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, key TEXT NOT NULL, fingerprint TEXT NOT NULL, status TEXT NOT NULL, payload TEXT, created_at TEXT NOT NULL, PRIMARY KEY(owner_id,key));
CREATE TABLE public_cache (key TEXT PRIMARY KEY, payload TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE request_limit (key TEXT PRIMARY KEY, count INTEGER NOT NULL, window INTEGER NOT NULL);
